version: '3'
services:
  eureka:
    image: ${REGISTER_URL}/${EUREKA_IMAGE}
    environment:
      RABBITMQ_HOST:
      RABBITMQ_USERNAME:
      RABBITMQ_PASSWORD:
      RABBITMQ_PORT:
      RABBITMQ_VHOST:
    ports:
    - "20000:20000"
    depends_on:
    - mq
    - redis
    entrypoint: /check-port.sh -d ${REDIS_HOST}:${REDIS_PORT},${RABBITMQ_HOST}:${RABBITMQ_PORT} -c '/usr/local/tomcat/bin/catalina.sh run';
  config:
    image: ${REGISTER_URL}/${CONFIG_IMAGE}
    environment:
      ADMIN_NAME:
      ADMIN_PASSWD:
      EUREKA_HOST:
      EUREKA_PORT:
      REDIS_HOST:
      REDIS_PORT:
      REDIS_PASSWORD:
      BASE_DRIVER:
      BASE_URL:
      BASE_USERNAME:
      BASE_PASSWORD:
      BPM_DRIVER:
      BPM_URL:
      BPM_USERNAME:
      BPM_PASSWORD:
      RABBITMQ_HOST:
      RABBITMQ_USERNAME:
      RABBITMQ_PASSWORD:
      RABBITMQ_PORT:
      RABBITMQ_VHOST:
      EUREKA_INSTANCE_IP-ADDRESS:
      EUREKA_INSTANCE_INSTANCE-ID:
      LUCKYUN_BASE:
      LUCKYUN_AUTH:
      LUCKYUN_OSS_PRO:
      LUCKYUN_REPORT:
    ports:
    - "8888:8888"
    - "8181:81"
    depends_on:
    - eureka
    entrypoint: /check-status.sh -d ${EUREKA_HOST}:${EUREKA_PORT} -c '/usr/local/tomcat/bin/start.sh';
  gateway:
    image: ${REGISTER_URL}/${GATEWAY_IMAGE}
    environment:
      EUREKA_HOST:
      EUREKA_PORT:
      EUREKA_INSTANCE_IP-ADDRESS:
      EUREKA_INSTANCE_INSTANCE-ID:
    ports:
    - "9998:9998"
    depends_on:
    - config
    entrypoint: /check-status.sh -d ${EUREKA_HOST}:${EUREKA_PORT}/eureka/apps/luckyun-config -c '/usr/local/tomcat/bin/catalina.sh run';
  auth:
    image: ${REGISTER_URL}/${AUTH_IMAGE}
    environment:
      EUREKA_HOST:
      EUREKA_PORT:
      EUREKA_INSTANCE_IP-ADDRESS:
      EUREKA_INSTANCE_INSTANCE-ID:
    ports:
    - "9991:9991"
    depends_on:
    - config
    entrypoint: /check-status.sh -d ${EUREKA_HOST}:${EUREKA_PORT}/eureka/apps/luckyun-config -c '/usr/local/tomcat/bin/catalina.sh run';
  base:
    image: ${REGISTER_URL}/${BASE_IMAGE}
    environment:
      EUREKA_HOST:
      EUREKA_PORT:
      EUREKA_INSTANCE_IP-ADDRESS:
      EUREKA_INSTANCE_INSTANCE-ID:
    ports:
    - "9096:9096"
    depends_on:
    - config
    entrypoint: /check-status.sh -d ${EUREKA_HOST}:${EUREKA_PORT}/eureka/apps/luckyun-config -c '/usr/local/tomcat/bin/catalina.sh run';
  bpm-api:
    image: ${REGISTER_URL}/${BPM_API_IMAGE}
    environment:
      EUREKA_HOST:
      EUREKA_PORT:
      EUREKA_INSTANCE_IP-ADDRESS:
      EUREKA_INSTANCE_INSTANCE-ID:
    ports:
    - "9201:9201"
    depends_on:
    - config
    entrypoint: /check-status.sh -d ${EUREKA_HOST}:${EUREKA_PORT}/eureka/apps/luckyun-config -c '/usr/local/tomcat/bin/catalina.sh run';
  oss:
    image: ${REGISTER_URL}/${OSS_IMAGE}
    environment:
      EUREKA_HOST:
      EUREKA_PORT:
      EUREKA_INSTANCE_IP-ADDRESS:
      EUREKA_INSTANCE_INSTANCE-ID:
    ports:
    - "9010:9010"
    depends_on:
    - config
    entrypoint: /check-status.sh -d ${EUREKA_HOST}:${EUREKA_PORT}/eureka/apps/luckyun-config -c '/data/apache-tocmat-9.0.26/bin/catalina.sh run';
  report:
    image: ${REGISTER_URL}/${REPORT_IMAGE}
    environment:
      EUREKA_HOST:
      EUREKA_PORT:
      EUREKA_INSTANCE_IP-ADDRESS:
      EUREKA_INSTANCE_INSTANCE-ID:
    ports:
    - "9093:9093"
    depends_on:
    - config
    entrypoint: /check-status.sh -d ${EUREKA_HOST}:${EUREKA_PORT}/eureka/apps/luckyun-config -c '/usr/local/tomcat/bin/catalina.sh run';
  mq:
    image: ${REGISTER_URL}/${MQ_IMAGE}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
    - "15672:15672"
    - "5672:5672"
  redis:
    image: ${REGISTER_URL}/${REDIS_IMAGE}
    environment:
      REDIS_PASSWORD:
    ports:
    - "6379:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}